/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Game Mode": "游戏模式",
    "Game Speed: x": "游戏速度: x",
    "Lv.": "等级",
    "Reload": "重新载入",
    "Sorry, there's nothing at this address.": "对不起，这个地址没有任何东西。",
    "An unhandled error has occurred.": "发生了一个未处理的错误。",
    "Device": "设备",
    "Home": "首页",
    "Ship Base": "飞船基地",
    "Idle Space War": "太空大战放置",
    "Common": "普通",
    "Attack Speed": "攻击速度",
    "AttackSpeed": "攻击速度",
    "Attack": "攻击",
    "AttackRange": "攻击范围",
    "Attack Range": "攻击范围",
    "Accuracy": "精准度",
    "Current Tier:": "当前层级:",
    "Critical Damage": "暴击伤害",
    "CriticalDamage": "暴击伤害",
    "CriticalRate": "暴击率",
    "Critical Rate": "暴击率",
    "DropRate": "掉率",
    "Drop Rate": "掉率",
    "Drops": "掉落",
    "Enemies:": "敌人:",
    "Rarity": "稀有度",
    "Rewards:": "奖励:",
    "ShadowGear": "暗影装备",
    "Uncommon": "罕见",
    "is destroyed": "被摧毁了",
    "FracturedCore": "破碎核心",
    "dropped": "掉落",
    "Planet Name:": "星球名称:",
    "Orbit Radius:": "轨道半径:",
    "Diary": "日记",
    "Attack to": "攻击",
    "Challenge": "挑战",
    "Currency Chart": "货币图表",
    "Debug Panel": "调试面板",
    "Dev Mode": "开发模式",
    "Ranking (Coming Soon)": "排行榜 (敬请期待)",
    "Reactor": "反应堆",
    "Reset Planet Tier": "重置星球层级",
    "Upgrade": "升级",
    "Unlocks by first Slow Attack Interval Challenge clear.": "通过第一次缓慢攻击间隔挑战解锁。",
    "(Lv.": "(等级",
    "Attack Booster": "攻击助推器",
    "Can attack enemies at any distance.": "可以攻击任何距离的敌人。",
    "Cognitive Enhancer": "认知增强器",
    "Critical hits DISABLED.": "暴击失效。",
    "EntropyNode:": "熵节点：",
    "Equip": "装备",
    "Equipped (": "已装备 (",
    "Fixed": "修复",
    "Fractured Core Drop Rate": "破碎核心 掉落率",
    "FracturedCore:": "破碎核心:",
    "Fractured Core Scanner:": "破碎核心扫描器:",
    "Launch Loot +2 when deployed.": "部署时启动战利品 +2.",
    "Max Target": "最大目标",
    "Move Speed": "移动速度",
    "Ninja": "忍者",
    "Old": "旧",
    "Planet Diary Old": "旧星球日记",
    "Regular": "标准",
    "Researcher": "研究员",
    "Resource Collection": "资源收集",
    "Salvage Instinct": "打捞本能",
    "Salvage Optimizer": "打捞优化器",
    "Ship Diary Old": "旧船日记",
    "Ship Name": "飞船名称",
    "Ship Stats": "飞船属性",
    "Ship Systems": "飞船系统",
    "Sniper Scope": "狙击范围",
    "Sniper Barrel": "狙击炮管",
    "Swarm": "蜂群",
    "Special Equipment": "特殊装备",
    "Starts with higher deployment capacity.": "初始拥有更高的部署容量。",
    "Tank": "油罐",
    "Targeting Radar": "瞄准雷达",
    "Undeployed": "未部署",
    "Thruster Module": "推进器模块",
    "Unequipped": "未装备",
    "Unlock": "解锁",
    "Unlocked by first Enemy Regen Challenge clear.": "完成第一个敌人回复挑战后解锁",
    "Unlocks by first Attack Decay Over Time Challenge clear.": "通过第一次攻击衰减时间挑战解锁",
    "Advanced Targeting": "高级瞄准",
    "Device Name": "设备名称",
    "Device Management": "设备管理",
    "Diary Progress Multiplier": "日记进度乘数",
    "Doubles the speed of Diary progress on all planets.": "所有星球上的日记进程速度加倍。",
    "Fractured Core Scanner": "破碎核心扫描器",
    "Rapid Reload": "快速装填",
    "QuantumFragment:": "量子碎片：",
    "Shadow Gear Drop Rate": "暗影装备掉落率",
    "Shadow Gear Scanner": "暗影装备扫描器",
    "ShadowGear:": "暗影装备:",
    "Deploy": "部署",
    "Assassin": "刺客",
    "DarkMatter:": "暗物质:",
    "Deployed": "已部署",
    "Diligent": "勤奋",
    "DimensionalSeal": "次元封印",
    "EntropyNode": "熵节点",
    "Epic": "史诗",
    "Gains increased experience from enemies.": "从敌人那里获得更多的经验。",
    "Gambler": "赌徒",
    "Instant Kill Chance": "秒杀几率",
    "Legendary": "传说",
    "MultiLock": "多重锁",
    "QuantumFragment": "量子碎片",
    "Rare": "稀有",
    "Scavenger": "清道夫",
    "Targets multiple enemies from the beginning (up to 10 targets).": "从一开始就瞄准多个敌人（最多10个目标）。",
    "This ship cannot move.": "该船无法移动。",
    "Unlocks by first Max Damage Cap Challenge clear.": "通过第一个最大伤害上限挑战解锁。",
    "Unlocks by first Halved Accuracy Challenge clear.": "通过第一个减半的精准度挑战解锁。",
    "Progress to defeat Enemy": "击败敌人的进度",
    "Progress to One Shot Kill Enemy": "一击击毙进度",
    "All ships have a fixed attack interval of 10 seconds during this challenge": "在这个挑战中，所有船只都有一个固定的10秒攻击间隔",
    "All ships have their accuracy reduced by half during this challenge": "在这次挑战中，所有船只的精度都会降低一半",
    "Attack Decay Over Time Challenge": "攻击随时间衰减挑战",
    "Attack power linearly decays over time during this challenge": "在这个挑战中，攻击能力会随着时间线性衰减",
    "Clear Reward:": "通关奖励：",
    "Clears:": "通关：",
    "Defeat an enemy on Emerald_Veil at Tier 10 or higher with halved accuracy": "在Emerald_Veil上击败一个10层或以上的敌人，精确度减半",
    "Defeat any enemy on Emerald_Veil at Tier 10 or higher before attack power decays too much": "在攻击强度衰减太多之前，击败翡翠面纱上10层或以上的任何敌人",
    "Each hit deals a maximum of 100 damage during this challenge": "在此挑战中，每次攻击最多造成100点伤害",
    "Enemies regenerate 100% of their HP every second during this challenge": "敌人在这个挑战中每秒回复100%的生命值",
    "Enemy Regen Challenge": "敌人回复挑战",
    "First Clear Reward:": "第一个明确奖励：",
    "Halved Accuracy Challenge": "半精度挑战",
    "Max Damage Cap Challenge": "最大伤害上限挑战",
    "Restriction:": "限制:",
    "Slow Attack Interval Challenge": "慢速攻击间隔挑战",
    "Starting the challenge will reset the planet’s tier.": "开始挑战将重置星球的层级。",
    "InfinityRange": "无限范围",
    "MaxTargets": "最大目标",
    "On": "开",
    "Planet Diary Regular": "星球日记普通",
    "Ship Diary Regular": "飞船日记普通",
    "Level": "等级",
    "ExpGain": "经验增益",
    "Cancel": "取消",
    "Amount": "数量",
    "Upgrade Name": "升级名称",
    "Add New Reactor": "增加新的反应堆",
    "Allows changing the ship’s targeting behavior": "允许改变飞船的瞄准行为",
    "Core Currencies": "核心货币",
    "Currencies": "货币",
    "Currency Name": "货币名称",
    "DamageCap": "伤害上限",
    "DarkMatter": "暗物质",
    "DebugPanelPage": "调试面板页",
    "Enable Log Scale": "启用日志缩放",
    "Energy Attack Converter": "能量攻击转换器",
    "Energy Attack Speed Converter": "能量攻击速度转换器",
    "Energy Critical Converter": "能量临界变换器",
    "Increases Attack based on current Space Energy amount": "根据当前空间能量增加攻击",
    "Increases Attack Speed based on current Space Energy amount": "根据当前空间能量增加攻击速度",
    "Increases Critical Damage based on current Space Energy amount": "根据当前空间能量增加暴击伤害",
    "InstantKillChance": "秒杀几率",
    "Is Agent Type Unlock": "座席类型是否解锁",
    "Max Ship Launches": "最大飞船运行",
    "MaxDeployCount": "最大部署数量",
    "MoveSpeed": "移动速度",
    "Multiplier Name": "乘数名称",
    "NanoAlloy": "纳米合金",
    "No Timer Upgrades yet.": "没有计时器升级。",
    "PhantomPart": "幻影部件",
    "PlayerExp": "玩家经验",
    "Prestige Reactor": "声望反应堆",
    "Reactor Amount Booster": "反应堆数量助推器",
    "Reactor Generate Amount": "反应堆发电量",
    "Reactor Generate Speed": "反应堆产生速度",
    "Reactor Speed Booster": "反应堆速度助推器",
    "Reactors": "反应堆",
    "Reactors produce energy over time. Use it wisely and Prestige to boost your power": "反应堆会随着时间产生能量。明智地使用它和声望来提升你的权力",
    "Reset Save Data": "重置保存数据",
    "Ship Move Stats": "船舶移动统计",
    "Sign in with Google": "用谷歌登录",
    "SignalChip": "信号芯片",
    "Space Crystal Upgrades": "太空水晶升级",
    "Space Crystal:": "空间水晶:",
    "Space Energy:": "空间能量:",
    "SpaceCrystal:": "太空水晶：",
    "SpaceEnergy:": "空间能量：",
    "SpecterCatalystId": "幽魂催化剂",
    "Start this challenge?": "开始这个挑战？",
    "StellarDust": "星尘",
    "Toggle Drop Materials": "切换掉落材料",
    "Toggle Drop Parameters": "切换掉落参数",
    "Unlock Ship Movement Mode": "解锁船舶移动模式",
    "Value": "价值",
    "- All Reactors and their levels will be lost.": "- 所有反应堆及其等级将会丢失。",
    "- All your": "- 你所有的",
    "+ You will gain": "+ 你会得到",
    "Are you sure you want to Prestige?": "你确定你想要声望吗？",
    "Are you sure you want to reset all save data? This action cannot be undone.": "您确定要重置所有保存的数据吗？此操作不能撤消。",
    "Confirm Reset": "确认重置",
    "Fill Time (s)": "填充时间（秒）",
    "Generate Amount": "生成数量",
    "Prestige": "声望",
    "Progress": "进度",
    "Reactor Name": "反应堆名称",
    "Reactor Timer Upgrade/0": "反应堆定时器升级/0",
    "Space Crystal": "空间水晶",
    "Space Energy": "空间能量",
    "will be reset.": "将被重置。",
    "Yes, Reset": "是的，重置",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "TigersEye_Nexus": "虎眼中枢",
    "PeachMorganite_Core": "红宝石_核心",
    "Moonstone_Glare": "月光石眩光",
    "Emerald_Veil": "翡翠面纱",
    "Amethyst_Prime": "紫晶至尊",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "?": "?",
    "s": "s",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Level up Reward : ": "升级奖励 : ",
    "Start exploring ": "开始探索 ",
    "Unlock Ship '": "解锁飞船 '",
    "Attack Speed + ": "攻击速度 + ",
    "Attack Range +": "攻击范围 +",
    "Critical Damage +": "暴击伤害 +",
    "Attack x (Clears + ": "攻击 x (清除 + ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "!": "!",
    "'": "'",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^\+([\d\.]+)\%$/,
    /^\/ ([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+) \[([\d\.]+)\]$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Defeat any enemy on Amethyst_Prime when tier is (.+) or higher$/, '在 紫晶至尊 上击败 $1 层级或更高层级的任何敌人'],
    [/^Each enemy defeated increases drop rate by (.+) on the planet. \(Defeated: (.+)\)$/, '每击败一个敌人，星球上的掉落概率 $1。（已击败：$2）'],
    [/^Clear Planet to Tier (.+) within (.+)s \(Elapsed: (.+)s, Remaining: (.+)s\)$/, '$2秒内通关星球至第$1层（耗时$3秒，剩余$4秒）'],
    [/^PlayerExp (.+)  \nDarkMatter (.+)  $/, '玩家经验 $1 \n暗物质 $2'],
    [/^Defeat (.+) enemies in Amethyst_Prime$/, '在 紫晶至尊 中击败 $1 个敌人'],
    [/^Defeat (.+) enemies in Emerald_Veil$/, '在 翡翠面纱 中击败 $1 个敌人'],
    [/^and dealt (.+) damage! (.+)$/, '并造成 $1 伤害! $2'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^DarkMatter \+ ([\d\.,]+)$/, '暗物质 \+ $1'],
    [/^Accuracy \+([\d\.,]+)$/, '精准度 \+$1'],
    [/^Enemy ([\d\.,]+)$/, '敌人 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Lv ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);